image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm --quiet --yes install && npm audit fix && npm run build
  - command: npm run serve

vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==
