image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      npm run prepare
      npm update
      npm audit fix
      npm install -g @vue/cli
      npm install cypress
    command: |
      echo "Starting Ambianic UI in dev mode:"
      npm run serve
  - command: |
      echo "Waiting for npm install to finish"
      gp await-port 8080 && gp preview $(gp url 8080)/index.html
      echo "Starting Ambianic PWA testsuite"
      npm run test
  - command: |
      echo "Starting http server for local HTML file preview"
      npx browser-sync start -s -w

# vscode:
#  extensions:
#    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true

