/**
Common mutation types
*/

export const PEER_DISCONNECTED = 'PEER_DISCONNECTED'
export const PEER_CONNECTING = 'PEER_CONNECTING'
export const PEER_CONNECTED = 'PEER_CONNECTED'
export const PNP_SERVICE_DISCONNECTED = 'PNP_SERVICE_DISCONNECTED'
export const PNP_SERVICE_CONNECTING = 'PNP_SERVICE_CONNECTING'
export const PNP_SERVICE_CONNECTED = 'PNP_SERVICE_CONNECTED'
export const USER_MESSAGE = 'USER_MESSAGE'
export const LAST_PEER_ID = 'LAST_PEER_ID'
export const NEW_PEER_ID = 'NEW_PEER_ID'
export const PEER_LAST_SERVER_ID = 'PEER_LAST_SERVER_ID'
