/**
Common mutation types
*/

export const PEER_CONNECTED = 'PEER_CONNECTED'
export const PEER_DISCONNECTED = 'PEER_DISCONNECTED'
export const PNP_SERVICE_CONNECTED = 'PNP_SERVICE_CONNECTED'
export const PNP_SERVICE_DISCONNECTED = 'PNP_SERVICE_DISCONNECTED'
